const {chromium}=require(process.env.GTD_E2E_PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const fixture=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
(async()=>{
 const browser=await chromium.launch({headless:true}),reports=[];
 try{for(const test of fixture.cases){
  const context=await browser.newContext({viewport:{width:test.width,height:1000},hasTouch:test.width<500}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000);
  await context.route('**/*',route=>route.request().url().startsWith(test.origin+'/')?route.continue():route.abort());
  const snapshot=()=>page.evaluate(()=>fetch('/api/v1/snapshot').then(r=>r.json())),fields=(state,id)=>state.entities.find(e=>e.id===id).frontmatter;
  const taskA='task-20261009-001',taskB='task-20261009-002',active='task-20261009-003';
  const card=id=>page.locator('[data-task-id="'+id+'"]').filter({visible:true}).first();
  const wait=async predicate=>{for(let i=0;i<100;i++){const state=await snapshot();if(predicate(state))return state;const confirm=page.locator('#confirm-preview');if(await confirm.isVisible())await confirm.click();await page.waitForTimeout(50);}throw Error('State did not arrive');};
  const menu=async id=>{await card(id).getByRole('button',{name:'操作',exact:true}).click();return page.getByRole('dialog',{name:'操作',exact:true});};
  const drag=async(id,key,touch=false)=>{
   const handle=card(id).getByRole('button',{name:'Taskをドラッグして操作',exact:true});await handle.scrollIntoViewIfNeeded();const b=await handle.boundingBox(),x=b.x+b.width/2,y=b.y+b.height/2;
   let cdp;if(touch){cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+12,y:y+12}]});}else{await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+12,y+12,{steps:3});}
   const dock=page.locator('[data-drag-destination="'+key+'"]');await dock.waitFor();const d=await dock.boundingBox(),tx=d.x+d.width/2,ty=d.y+d.height/2;
   if(touch){for(let n=1;n<=5;n++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+(tx-x)*n/5,y:y+(ty-y)*n/5}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await page.mouse.move(tx,ty,{steps:5});await page.mouse.up();}
  };
  await page.goto(test.origin+'/tasks');await card(taskA).waitFor();
  assert.equal(await card(taskA).locator('.card-actions > button').count(),1,'One operations trigger replaces date/due/start buttons');
  let before=await snapshot(),measured=fields(before,active);const operationMenu=await menu(taskA);assert.equal(await operationMenu.getByRole('button',{name:'開始',exact:true}).count(),1);assert.equal(await operationMenu.getByRole('button',{name:'完了',exact:true}).count(),1);assert.equal(await operationMenu.getByRole('button',{name:/時刻/}).count(),0);assert.equal(await operationMenu.locator('details').getAttribute('open'),null);await page.keyboard.press('Escape');assert.deepEqual(await snapshot(),before);
  await drag(taskA,'start',test.width<500);await page.locator('#task-switch-dialog').waitFor();assert.deepEqual(fields(await snapshot(),active),measured,'Start drop does not finish existing measurement');await page.locator('#cancel-task-switch').click();assert.deepEqual(await snapshot(),before);
  await drag(taskA,'dated',test.width<500);await page.locator('#focus-move-dialog').waitFor();await page.locator('#focus-move-date').fill('2026-10-12');await page.locator('#focus-move-cancel').click();assert.deepEqual(await snapshot(),before,'Date cancellation writes nothing');
  await drag(taskA,'today',test.width<500);await wait(s=>Boolean(fields(s,taskA).action_date));
  await (await menu(taskA)).getByRole('button',{name:'予定日なし',exact:true}).click();await wait(s=>!fields(s,taskA).action_date);
  const todayMenu=await menu(taskA);await todayMenu.getByRole('button',{name:'今日やる',exact:true}).click();await wait(s=>Boolean(fields(s,taskA).action_date));
  const completed=await menu(taskA);await completed.getByRole('button',{name:'完了',exact:true}).click();await wait(s=>fields(s,taskA).status==='done');assert.deepEqual(fields(await snapshot(),active),measured);assert.equal(fields(await snapshot(),taskA).work_started_at,undefined,'Unstarted completion invents no actual');
  await page.locator('#task-completed-details').evaluate(e=>e.open=true);const all=page.locator('#completed-period-toggle');if(await all.isVisible()&&await all.innerText()==='過去の完了も表示')await all.click();
  assert.equal(await (await menu(taskA)).getByRole('button',{name:'完了取消',exact:true}).count(),0);await page.keyboard.press('Escape');
  const source='task-20261009-004',original=fields(await snapshot(),source);before=await snapshot();
  await drag(source,'continue',test.width<500);let destination=page.getByRole('dialog',{name:'続きのTaskを作る',exact:true});await destination.getByRole('button',{name:'日付を選ぶ',exact:true}).click();await destination.getByLabel('コピー先の日付').fill('2026-10-12');await destination.getByRole('button',{name:'キャンセル',exact:true}).click();assert.deepEqual(await snapshot(),before,'Copy date cancellation changes neither original nor copies');
  const copies=async id=>(await snapshot()).entities.filter(e=>e.frontmatter?.continuation_of===id);
  await (await menu(source)).getByRole('button',{name:'続きのTaskを作る',exact:true}).click();destination=page.getByRole('dialog',{name:'続きのTaskを作る',exact:true});await destination.getByRole('button',{name:'今日やる',exact:true}).evaluate(e=>{e.click();e.click();});await wait(s=>s.entities.some(e=>e.frontmatter?.continuation_of===source));assert.equal((await copies(source)).length,1,'Double click creates one continuation');let copy=(await copies(source))[0];assert.ok(copy.frontmatter.action_date);assert.equal(copy.frontmatter.work_started_at,undefined);assert.equal(copy.frontmatter.calendar_event_id,undefined);assert.deepEqual(fields(await snapshot(),source),original,'Original actual and status remain unchanged');assert.deepEqual(fields(await snapshot(),active),measured);
  await (await menu(source)).getByRole('button',{name:'続きのTaskを作る',exact:true}).click();destination=page.getByRole('dialog',{name:'続きのTaskを作る',exact:true});await destination.getByRole('button',{name:'日付を選ぶ',exact:true}).click();await destination.getByLabel('コピー先の日付').fill('2026-10-12');await destination.getByRole('button',{name:'この日付で作る',exact:true}).click();await wait(s=>s.entities.filter(e=>e.frontmatter?.continuation_of===source).length===2);assert.equal((await copies(source)).filter(e=>e.frontmatter.action_date==='2026-10-12').length,1);assert.deepEqual(fields(await snapshot(),source),original);
  // Lose a successful create response, then reconcile that exact issued copy ID.
  let dropped=false;await page.route('**/api/v1/mutations/apply',async route=>{if(!dropped&&route.request().postDataJSON()?.preview?.operation?.action==='create'){dropped=true;await route.fetch();await route.abort('failed');}else await route.continue();});
  await (await menu(taskA)).getByRole('button',{name:'続きのTaskを作る',exact:true}).click();await page.getByRole('dialog',{name:'続きのTaskを作る',exact:true}).getByRole('button',{name:'予定日なし',exact:true}).click();await page.locator('#retry-current').waitFor({state:'visible'});assert.equal((await copies(taskA)).length,1);assert.equal(await card(taskA).getByRole('button',{name:'操作',exact:true}).isDisabled(),true);await page.locator('#retry-current').click();await page.locator('#retry-current').waitFor({state:'hidden'});await wait(s=>s.entities.some(e=>e.frontmatter?.continuation_of===taskA));await page.waitForTimeout(100);assert.equal((await copies(taskA)).length,1,'Unknown response reconciliation does not create another copy');assert.equal((await copies(taskA))[0].frontmatter.action_date,undefined);assert.equal(fields(await snapshot(),taskA).status,'done');await page.unroute('**/api/v1/mutations/apply');
  await (await menu(taskB)).getByRole('button',{name:'開始',exact:true}).click();await page.locator('#task-switch-dialog').waitFor();assert.deepEqual(fields(await snapshot(),active),measured);await page.keyboard.press('Escape');assert.deepEqual(fields(await snapshot(),active),measured);
  const current=await menu(active);assert.equal(await current.getByRole('button',{name:'中断',exact:true}).count(),1);assert.equal(await current.getByRole('button',{name:'完了',exact:true}).count(),1);await page.keyboard.press('Escape');
  assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(fixture.output,'task-operations-'+test.width+'.png'),fullPage:true});
  reports.push({width:test.width,touch:test.width<500,sharedStateAndDateActions:true,startSwitchCancelledPreservesMeasured:true,dateCancelledNoWrite:true,repeatedMoves:true,completedContinuationPreservesActual:true,copyDateCancelledNoWrite:true,doubleClickCreatesOnce:true,unknownCopyReadbackNoDuplicate:true,pageErrors:errors});await context.close();
 }
 fs.writeFileSync(path.join(fixture.output,'qa.json'),JSON.stringify(reports,null,2));console.log(JSON.stringify(reports));
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
